apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tonic-web-server
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-web-server
    spec:
      containers:
      - env:
        {{- range $key, $value := .Values.tonicai.web_server.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: TONIC_DB_DATABASE
          value: {{ .Values.tonicdb.dbName }}
        - name: TONIC_DB_USERNAME
          value: {{ .Values.tonicdb.user }}
        - name: TONIC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tonic-db-password
              key: password
        - name: TONIC_DB_PORT
          value: {{quote .Values.tonicdb.port }}
        - name: TONIC_DB_SSLMODE
          value: {{ .Values.tonicdb.sslMode }}
        - name: TONIC_DB_HOST
          value: {{ .Values.tonicdb.host }}
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        image: quay.io/tonicai/tonic_web_server:{{ .Values.tonicVersion }}
        imagePullPolicy: Always
        name: tonic-web-server
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "3Gi"
          requests:
            memory: "2Gi"
            ephemeral-storage: "1Gi"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ps -ef | grep Allos.Api.dll | grep -v grep
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ps -ef | grep Allos.Api.dll | grep -v grep
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
      serviceAccountName: {{ template "tonic.serviceAccountName" . }}
      imagePullSecrets:
      - name: tonicai-build-writer-pull-secret
      volumes: null
status: {}
